---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eval=TRUE}
library(quanteda)
library(dplyr)
library(tidyverse)
library(utf8)
library(ggplot2)

setwd("C:/Users/Dieca/OneDrive/Escritorio")
primer_tiempo2020 <- read_csv("Primer_Tiempo2020.csv",col_names = TRUE)
#str(primer_tiempo2020)
attach(primer_tiempo2020)

summary(primer_tiempo2020)


## Borrar Datos Char

primer_tiempo2020
primer_tiempo2020 <- primer_tiempo2020[,!(colnames(primer_tiempo2020) %in% c("id_partido", "fasepartido", "local", "tiempo","formationUsed", "torneo"))]
primer_tiempo2020


## Analisis descriptivo


fh2020 <- primer_tiempo2020[order(primer_tiempo2020$goalAssist, decreasing = TRUE),]
fh2020

## Sub DataFrames

fh2020_corners = fh2020[,colnames(primer_tiempo2020) %in% c( "equipo", "lostCorners", "partido", "wonCorners", "cornerTaken", "shotogTarget")]
fh2020_corners = fh2020_corners[order(fh2020_corners$wonCorners, decreasing = TRUE),]
fh2020_corners
fh2020_fauls <- NULL
fh2020_fauls = fh2020[,colnames(primer_tiempo2020) %in% c("equipo", "partido", "totalTackle", "totalYellowCard", "fkFoulWon", "fkFoulLost", "totalOffside", "totalRedCard")]

#fh2020_fauls = fh2020_fauls[order(fh2020_tiros$totalYellowCard, decreasing = TRUE),]
#fh2020_fauls


## Filtrar Datos
Palestino <- filter(primer_tiempo2020, equipo == "Palestino")
Palestino_corners <- filter(fh2020_corners, equipo == "Palestino")
Palestino_fauls <- filter(fh2020_fauls, equipo == "Palestino")


## Agregar Promedio/Suma Total/Min/...

Palestino_corners <- Palestino_corners[,!(colnames(Palestino_corners) %in% c("equipo"))] 
Promedios_corners <- c("Promedio de Corners",mean(Palestino_corners$lostCorners),mean(Palestino_corners$wonCorners),mean(Palestino_corners$cornerTaken))
Palestino_corners <- rbind(Palestino_corners, Promedios_corners)

Max_Corners <- c("Max de Corners",max(Palestino_corners$lostCorners),max(Palestino_corners$wonCorners),max(Palestino_corners$cornerTaken))
Palestino_corners <- rbind(Palestino_corners, Max_Corners)

Min_corners <- c("Min corners",min(Palestino_corners$lostCorners),min(Palestino_corners$wonCorners),min(Palestino_corners$cornerTaken))
Palestino_corners <- rbind(Palestino_corners, Min_corners)
Palestino_corners

## Graficos

rendimiento_everton <- Palestino$goalAssist
Palestino2 <- Palestino[order(Palestino$goalAssist, decreasing = FALSE),]
dotchart(Palestino$goals, labels = Palestino$partido, cex=0.5, xlab = "goles", ylab = "Partido")
dotchart(Palestino$totalPass, labels = utf8_encode(Palestino$partido), cex=0.5, xlab = "pases", ylab = "Partido")
dotchart(Palestino$accuratePass, labels = utf8_encode(Palestino$partido), cex=0.5, xlab = "pases", ylab = "Partido")
dotchart(Palestino$goalsConceded, labels = utf8_encode(Palestino$partido), cex=0.5, xlab = "goles concedidos", ylab = "Partido")
dotchart(Palestino$goalAssist, labels = utf8_encode(Palestino$partido), main="asistenicias", pch = 16, col=c("darkblue","dodgerblue"),lcolor="gray90", cex=0.8, xlab = "asistencias", ylab = "Partido", cex.main=2,cex.lab=1.5)


## Analisis de Texto

texto <- primer_tiempo2020$partido
texto <- char_tolower(texto)
texto <- iconv(texto, to = "ASCII//TRANSLIT")
a <- dfm(texto, remove = c(stopwords("es"), "vs", "Universidad"))
dim(a)

```
